<%@page import="java.util.Calendar"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<!DOCTYPE html >
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>A1 Sport</title>
<link rel="stylesheet" href="css/style.css">
</head>
<body>

	<header id="home" class="header">
		<nav class="nav" role="navigation">
			<div class="container nav-elements">
				<div class="branding">
					<a href="#home"><img src="images/a1sportlogo.svg"
						alt="Logo - H Plus Sports"></a>
				</div>
				<!-- branding -->
				<ul class="navbar">
					<li><a href="home">home</a></li>
					<li><a href="orderHistory">order history</a></li>
					<!-- <li><a href="viewProfile">view my profile</a></li> -->
					<li><a href='<%=response.encodeURL("viewProfile")%>'>view
							my profile</a></li>
					<li><a href='logout'>logout</a></li>
					<li><a href="redirect">linkedIn</a></li>

				</ul>
				<!-- navbar -->
			</div>
			<!-- container nav-elements -->
		</nav>
		<!-- <div class="container tagline">
    <h1 class="headline">Our Mission</h1>
   <p>We support and encourage active and healthy lifestyles, by offering high performance products for the result-driven athlete.</p>
  </div>container tagline -->
	</header>
	
<!-- DocPoint 51. Get the profile information from the request scope.
	Display the user properties with usebean.

 -->
	<jsp:useBean id="user" scope="request" type="com.test.beans.User"></jsp:useBean>
	<section>

		<ex:formatDate date="<%=Calendar.getInstance().getTime()%>"
			format="dd-MM-YYYY hh:mm"></ex:formatDate>
	</section>
	
	<section id="profile" class="section">
		<div class="container">
			<h2 class="headline">My Profile</h2>
			<table id="profile">

				<tr>
					<td>Username</td>
					<td><jsp:getProperty property="username" name="user" /></td>
				</tr>
				<tr>
					<td>First Name</td>
					<td><jsp:getProperty property="firstName" name="user" /></td>
				</tr>
				<tr>
					<td>Last Name</td>
					<td><jsp:getProperty property="lastName" name="user" /></td>
				</tr>
				<tr>
					<td>Age</td>
					<td>${user.age}</td>
				</tr>
				<tr>
					<td>Interested in</td>
					<td>${user.activity}</td>
				</tr>

			</table>
		</div>
	</section>



	<footer class="footer">
		<div class="container">
			<nav class="nav" role="navigation">
				<div class="container nav-elements">
					<div class="branding">
						<a href="#home"><img src="images/a1sportlogo.svg"
							alt="Logo - H Plus Sports"></a>
						<p class="address">
							1906 N Main Ave<br> San Antonio, TX 78212
						</p>
					</div>
				</div>
			</nav>
			<p class="legal">Everything on this page is not real.  The people
			are generated by AI.</p>
		</div>
		<!-- container -->
	</footer>
	<!-- footer -->


</body>
</html>